name: Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
    - uses: actions/checkout@v3
    - run: make test
